original_root: /wekafs/ict/ict_vgl/multi_view_dataset/spatialvid
root: /wekafs/ict/junyiouy/map_anything_data/spatialvid

dataset_name: spatialvid
version: 0.1
overwrite: True

scene_filters:
  - process_state_not: [conversion, finished]
