defaults:
  - lower_encoder_lr_ste3lr

# Optimizer parameters specific to submodules
submodule_configs:
  # Encoder
  encoder:
    lr: 5e-06
    min_lr: 5e-08
    warmup_epochs: ${train_params.warmup_epochs}
    weight_decay: ${train_params.weight_decay}
    schedule_type: ${train_params.schedule_type}
  # Boost LR for the new Router inside Transformer
  # This assumes get_parameter_groups supports nested matching (info_sharing.router)
  info_sharing.router:
    lr: 1e-3
    min_lr: 1e-4
    warmup_epochs: ${train_params.warmup_epochs}
    weight_decay: ${train_params.weight_decay}
    schedule_type: ${train_params.schedule_type}
  view_compressions:
    lr: 1e-3
    min_lr: 1e-4
    warmup_epochs: ${train_params.warmup_epochs}
    weight_decay: ${train_params.weight_decay}
    schedule_type: ${train_params.schedule_type}