defaults:
  - default

# Optimizer parameters specific to submodules
submodule_configs:
  # Encoder
  encoder:
    lr: 0
  info_sharing.self_attention_blocks.0.:
    lr: 0
  info_sharing.self_attention_blocks.1.:
    lr: 0
  info_sharing.self_attention_blocks.2.:
    lr: 0
  info_sharing.self_attention_blocks.3.:
    lr: 0
  info_sharing.self_attention_blocks.4.:
    lr: 0
  info_sharing.self_attention_blocks.5.:
    lr: 0
  info_sharing.self_attention_blocks.6.:
    lr: 0
  info_sharing.self_attention_blocks.7.:
    lr: 0
  info_sharing.self_attention_blocks.8.:
    lr: 0
  info_sharing.self_attention_blocks.9.:
    lr: 0
  info_sharing.self_attention_blocks.10.:
    lr: 0
  info_sharing.self_attention_blocks.11.:
    lr: 0
  info_sharing.self_attention_blocks.12.:
    lr: 0
  info_sharing.self_attention_blocks.13.:
    lr: 0
  info_sharing.self_attention_blocks.14.:
    lr: 0
  info_sharing.self_attention_blocks.15.:
    lr: 0