defaults:
  - default

# Number of views parameter for the multi-view datasets
num_views: 2

# Test Resolution
resolution_test_scannetpp: ${dataset.resolution_options.518_1_52_ar}

# Test Set
# Sample 10 multi-view sets from each scene
# ScanNet++V2: 30 scenes
test_dataset:
  "+ 300 @ ${dataset.scannetpp_wai.test.dataset_str}"
